### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/epuck_ros2#9]
The packages (especially `epuck_ros2_cpp`) are missing detailed documentation. Readme files such as the following two should be created:
- https://github.com/cyberbotics/webots_ros2/tree/epuck2/webots_ros2_epuck2
- https://github.com/cyberbotics/epuck_ros2/tree/master/epuck_ros2_camera

**Comment by lukicdarkoo** [comment]
A huge amount of content required for the documentation can be shared with `webots_ros2_epuck`:
https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_epuck/README.md

How do we handle this? Do we copy and change the specific details, or we create common documentation + documentation specific to `webots_ros2_epuck` and `epuck_ros2_cpp` separately?

**Comment by omichel** [comment]
We should never copy as the copies will inevitably diverge at some point.
The best is to document at one place and set a pointer to this documentation at the other place(s).
